# Generated by Django 5.0.4 on 2024-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('E', 'Euro'), ('U', 'US Dollars'), ('G', 'British Pounds')], default='E', max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=6)),
            ],
        ),
    ]
