# Generated by Django 5.0.4 on 2024-04-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
