# Generated by Django 5.0.4 on 2024-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_accountholder_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
