# Generated by Django 5.0.4 on 2024-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_accountholder_set_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='currency',
            field=models.CharField(choices=[('Euro', 'Euro'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='Euro', max_length=4),
        ),
    ]
