# Generated by Django 5.0.4 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_accountholder_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='EUR', max_length=4),
        ),
    ]
