# Generated by Django 5.0.4 on 2024-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='EUR', max_length=3),
        ),
    ]
