# Generated by Django 5.0.4 on 2024-04-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_request',
        ),
    ]
