# Generated by Django 5.0.4 on 2024-04-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_remove_transaction_is_completed_and_more'),
        ('register', '0011_alter_accountholder_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('req_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='register.accountholder')),
                ('req_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='register.accountholder')),
            ],
        ),
    ]
