# Generated by Django 5.0.4 on 2024-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
